"""Added review model for database

Revision ID: 2134a3241c7e
Revises: 7fcdc7da0d5c
Create Date: 2026-04-26 17:59:35.548492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2134a3241c7e'
down_revision: Union[str, Sequence[str], None] = '7fcdc7da0d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_category_id'), 'lots', ['category_id'], unique=False)
    op.add_column('users', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Numeric(precision=10, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    op.drop_column('users', 'reviews_count')
    op.drop_index(op.f('ix_lots_category_id'), table_name='lots')
    op.drop_table('reviews')
    # ### end Alembic commands ###
