"""Added buying_message for lot

Revision ID: 39f18017dab2
Revises: db4906aca43e
Create Date: 2026-05-03 12:23:41.491463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f18017dab2'
down_revision: Union[str, Sequence[str], None] = 'db4906aca43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('buying_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'buying_message')
    # ### end Alembic commands ###
