"""Added status column for order table

Revision ID: db4906aca43e
Revises: e6908c4dcfe5
Create Date: 2026-05-02 16:14:58.369537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4906aca43e'
down_revision: Union[str, Sequence[str], None] = 'e6908c4dcfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('close_time', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'is_complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'close_time')
    op.drop_column('orders', 'create_time')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
