"""Added seller relationship to order table

Revision ID: f8516b4eeecd
Revises: 39f18017dab2
Create Date: 2026-05-04 11:11:42.016124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8516b4eeecd'
down_revision: Union[str, Sequence[str], None] = '39f18017dab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'seller_id')
    # ### end Alembic commands ###
